In [1]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBClassifier

In [2]:
import pandas as pd

# Read each CSV file into separate DataFrames
df1 = pd.read_csv('/content/1996_data.csv')
df2 = pd.read_csv('/content/2000_data.csv')
df3 = pd.read_csv('/content/2002_data.csv')
df4 = pd.read_csv('/content/2003.csv')
df5 = pd.read_csv('/content/2007_data.csv')

# Merge the DataFrames
merged_df = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)

# Save the merged DataFrame to a new CSV file
merged_df.to_csv('merged_file.csv', index=False)

In [3]:
merged_df.shape

(150000, 30)

In [4]:
merged_df.head()

,year,month,dayofmonth,dayofweek,deptime,crsdeptime,arrtime,crsarrtime,uniquecarrier,flightnum,...,taxiout,cancelled,cancellationcode,diverted,carrierdelay,weatherdelay,nasdelay,securitydelay,lateaircraftdelay,delayed
0,1996,12,15,7,1605.0,0,1804.0,0,AA,1481,...,16,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Y
1,1996,2,5,1,1242.0,1240,1533.0,1541,UA,286,...,10,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Y
2,1996,12,28,6,1335.0,1330,1606.0,1610,DL,1183,...,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Y
3,1996,12,10,2,857.0,0,1117.0,0,AA,1689,...,12,0,NaN,0,NaN,NaN,NaN,NaN,NaN,N
4,1996,10,5,6,1420.0,1420,1459.0,1505,WN,1364,...,9,0,NaN,0,NaN,NaN,NaN,NaN,NaN,N

In [5]:
# Calculate the number of null values in each column
null_values = merged_df.isnull().sum()
null_values

year                      0
month                     0
dayofmonth                0
dayofweek                 0
deptime                3167
crsdeptime                0
arrtime                3495
crsarrtime                0
uniquecarrier             0
flightnum                 0
tailnum                 284
actualelapsedtime      3495
crselapsedtime           23
airtime                3495
arrdelay               3495
depdelay               3167
origin                    0
dest                      0
distance                  0
taxiin                    0
taxiout                   0
cancelled                 0
cancellationcode     149124
diverted                  0
carrierdelay         102288
weatherdelay         102288
nasdelay             102288
securitydelay        102288
lateaircraftdelay    102288
delayed                   0
dtype: int64

In [6]:
# Calculate the percentage of null values in each column
null_percentage = merged_df.isnull().mean() * 100
null_percentage

year                  0.000000
month                 0.000000
dayofmonth            0.000000
dayofweek             0.000000
deptime               2.111333
crsdeptime            0.000000
arrtime               2.330000
crsarrtime            0.000000
uniquecarrier         0.000000
flightnum             0.000000
tailnum               0.189333
actualelapsedtime     2.330000
crselapsedtime        0.015333
airtime               2.330000
arrdelay              2.330000
depdelay              2.111333
origin                0.000000
dest                  0.000000
distance              0.000000
taxiin                0.000000
taxiout               0.000000
cancelled             0.000000
cancellationcode     99.416000
diverted              0.000000
carrierdelay         68.192000
weatherdelay         68.192000
nasdelay             68.192000
securitydelay        68.192000
lateaircraftdelay    68.192000
delayed               0.000000
dtype: float64

In [7]:
# Identify columns with more than 65% null values
columns_to_drop = null_percentage[null_percentage > 65].index

# Drop columns with more than 65% null values
merged_df.drop(columns=columns_to_drop, inplace=True)

In [8]:
# Calculate the number of null values in each column
null_values = merged_df.isnull().sum()
null_values

year                    0
month                   0
dayofmonth              0
dayofweek               0
deptime              3167
crsdeptime              0
arrtime              3495
crsarrtime              0
uniquecarrier           0
flightnum               0
tailnum               284
actualelapsedtime    3495
crselapsedtime         23
airtime              3495
arrdelay             3495
depdelay             3167
origin                  0
dest                    0
distance                0
taxiin                  0
taxiout                 0
cancelled               0
diverted                0
delayed                 0
dtype: int64

In [9]:
merged_df.dtypes

year                   int64
month                  int64
dayofmonth             int64
dayofweek              int64
deptime              float64
crsdeptime             int64
arrtime              float64
crsarrtime             int64
uniquecarrier         object
flightnum              int64
tailnum               object
actualelapsedtime    float64
crselapsedtime       float64
airtime              float64
arrdelay             float64
depdelay             float64
origin                object
dest                  object
distance               int64
taxiin                 int64
taxiout                int64
cancelled              int64
diverted               int64
delayed               object
dtype: object

In [ ]:
# For numerical columns, you might use mean, median, or a specific value
numerical_cols = ['deptime', 'arrtime', 'actualelapsedtime', 'crselapsedtime', 'airtime', 'arrdelay', 'depdelay']
for col in numerical_cols:
    merged_df[col].fillna(merged_df[col].median(), inplace=True)

In [ ]:
# For categorical columns, you might use the mode (most frequent value) or a
# specific value'

categorical_col = ['uniquecarrier ','tailnum', 'origin','dest', 'delayed']
for col in categorical_col:
    merged_df[col].fillna(merged_df[col].mode()[0], inplace=True)

KeyError: 'uniquecarrier '